#!/bin/bash

# stocks is client-server program to manage a household's food stock
# Copyright (C) 2019  The stocks developers
#
# This file is part of the stocks program suite.
#
# stocks is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# stocks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "master" -o \
        "$BRANCH" = "dev-server" -o \
        "$BRANCH" = "dev-client" -o \
        "$BRANCH" = "dev-android" ] ; then
        exit 0
else
        if ! cat $1 | head -n 1 | egrep '^Issue #[0-9]+ .*$' -q ; then
            echo "First line must start with issue number"
            exit 1
        fi

        if [[ "$(egrep -v '^#' $1 | wc -l)" -eq 1 ]] ; then
            exit 0
        fi

        if ! cat $1 | head -n 2 | tail -n 1 | egrep '^$' -q ; then
            echo "Second line must be empty"
            exit 1
        fi
fi
