#!/bin/sh

# stocks is client-server program to manage a household's food stock
# Copyright (C) 2019  The stocks developers
#
# This file is part of the stocks program suite.
#
# stocks is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# stocks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# verify client version number

CLIENTVERSION=$(grep "<version>" client/pom.xml | \
        head -n 1 | \
        sed 's$ *<version>\(.*\)</version>$\1$g')
CLIENTVERSIONJAVA=$(echo ${CLIENTVERSION} | sed 's/\./_/g' |
        sed 's/\(.*\)_.*/\1/g' )
CLIENTVERSIONDB=$(echo ${CLIENTVERSIONJAVA} | sed 's/_/./g' )

if ! grep "pkgver=${CLIENTVERSION}" deploy-client/PKGBUILD >/dev/null 2>&1 ;
then
        echo "client PKGBUILD version differs from pom.xml"
        exit 1
fi

if ! grep "public static final Version CURRENT = V_${CLIENTVERSIONJAVA}" \
        client/src/main/java/de/njsm/stocks/client/init/upgrade/Version.java >/dev/null 2>&1 ;
then
        echo "client Version.java version differs"
        exit 1
fi

if ! grep "('db.version', '$CLIENTVERSIONDB')" \
        deploy-client/config/schema.sql >/dev/null 2>&1 ;
then
        echo "client schema.sql version differs"
        exit 1
fi

# SERVER

SERVERVERSION="$(grep pkgver= deploy-server/PKGBUILD \
        | sed 's/pkgver=//')"

if ! egrep "^    <version>$SERVERVERSION</version>$" \
        server/pom.xml >/dev/null 2>&1 ;
then
        echo "server pom.xml version differs from PKGBUILD"
        exit 1
fi
