language: java
jdk:
        - oraclejdk8
script:
        - cd server
        - mvn test
        - cd ../sentry
        - mvn test
        - cd ../client
        - mvn test

notifications:
        email: false
