#!/bin/sh

cd server
mvn compile package
cd ..
cp server/target/server-0.1-beta.war jetty-base/wars/server.war

cd sentry
mvn compile package
cd ..
cp sentry/target/sentry-0.1-beta.war jetty-base/wars/sentry.war
