package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.ScheduleTrigger
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    triggers {
        val trigger1 = find<ScheduleTrigger> {
            schedule {
                schedulingPolicy = cron {
                    minutes = "4,14,24,34,44,54"
                    dayOfWeek = "*"
                }
                branchFilter = "+:STOCKS-63"
                triggerBuild = always()
                withPendingChangesOnly = false
                param("hour", "1")
                param("revisionRuleDependsOn", "Stocks_Build")
            }
        }
        trigger1.apply {
            enabled = false
        }
    }
}
