# stocks is client-server program to manage a household's food stock
# Copyright (C) 2019  The stocks developers
#
# This file is part of the stocks program suite.
#
# stocks is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# stocks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

- hosts: stocks_client

  vars:
      remote_pkg_dir: /tmp
      stocks_pkg_dir: "{{ playbook_dir }}"

  remote_user: root
  tasks:
    - name: Lookup package file
      local_action:
        module: find
        paths: "{{ stocks_pkg_dir }}"
        patterns: 'stocks-server-*.pkg.tar.zst'
      register: found_files

    - name: Set package name
      set_fact:
        package: "{{ found_files.files | sort(attribute='path') | last }}"

    - name: Copy package
      copy:
        src: "{{ package.path }}"
        dest: "{{ remote_pkg_dir }}"
      register: copied_file

    - name: Install stocks package
      command: "pacman --noconfirm -U {{ copied_file.dest }}"
