package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.projectFeatures.githubConnection
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        remove {
            githubConnection {
                id = "PROJECT_EXT_2"
                displayName = "GitHub.com"
                clientId = "133b8d6e9faa4d280817"
                clientSecret = "credentialsJSON:90a997d8-4176-441e-8112-3ddee1038ca8"
            }
        }
    }
}
