package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGitlabComVeenjStocksGit'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGitlabComVeenjStocksGit")
    name = "https://gitlab.com/veenj/stocks.git"
    url = "https://gitlab.com/veenj/stocks.git"
    branch = "master"
    param("oauthProviderId", "PROJECT_EXT_3")
    param("tokenType", "undefined")
}))

