- hosts: deployment-test
  vars:
          stocks_version: 0.4-1
          local_user: jan
          remote_user: jan

  remote_user: root
  tasks:
  - name: Copy package
    copy: src=~/Software/stocks-server/stocks-server-{{ stocks_version }}-x86_64.pkg.tar.xz dest=/home/jan/Software/

  - name: Install stocks package
    command: pacman -U /home/jan/Software/stocks-server-{{ stocks_version }}-x86_64.pkg.tar.xz --noconfirm
    become: yes
