- hosts: "{{ target_host | default('deployment-test')}}"

  vars:
      remote_pkg_dir: /tmp
      
      stocks_pkg_dir: "{{ playbook_dir }}/target"
      stocks_version: 1.0.2-1
      stocks_pkg: stocks-server-{{ stocks_version }}-any.pkg.tar.xz


  remote_user: root
  tasks:
  - name: Copy package
    copy: >
        src={{ stocks_pkg_dir }}/{{ stocks_pkg }}
        dest={{ remote_pkg_dir }}

  - name: Install stocks package
    command: pacman -U {{ remote_pkg_dir }}/{{ stocks_pkg }} --noconfirm
