#!/usr/bin/sh

if [[ $# -ne 2 ]] ; then
    echo "Usage: setup-ca.sh <target-dir> <config-template-dir>"
    exit 1
fi

CA_ROOT=$1
CONFIG_TEMPLATE_DIR=$2
RANDFILE=$CA_ROOT/.rnd

## Set up the CA
    mkdir -p $CA_ROOT
    cd $CA_ROOT
    cp $CONFIG_TEMPLATE_DIR/openssl.cnf .
    sed -i "s&@@@CAROOT@@@&$CA_ROOT&g" openssl.cnf
    mkdir certs csr private newcerts crl
    chmod 700 private
    touch index.txt
    echo 1000 > serial
    echo 1000 > crlnumber
    openssl genrsa -out private/ca.key.pem 4096
    chmod 400 private/ca.key.pem
    openssl req -config openssl.cnf -key private/ca.key.pem -new -x509 -days 365000 -sha256 -extensions v3_ca -out certs/ca.cert.pem \
        -subj "/C=CH/ST=Zurich/L=Zurich/O=stocks/CN=stocks CA" -batch
    openssl ca -config openssl.cnf -gencrl -out crl/ca.crl.pem
    chmod 444 certs/ca.cert.pem
    
    ## Set up intermediate CA
    mkdir -p intermediate
    cd intermediate
    cp $CONFIG_TEMPLATE_DIR/openssl.cnf .
    sed -i "s&@@@CAROOT@@@&$CA_ROOT&g" openssl.cnf
    mkdir certs csr private newcerts crl
    chmod 700 private
    touch index.txt
    echo 1000 > serial
    echo 1000 > crlnumber
    openssl genrsa -out private/intermediate.key.pem 4096
    chmod 400 private/intermediate.key.pem
    openssl req -config openssl.cnf -new -sha256 -key private/intermediate.key.pem -out csr/intermediate.csr.pem \
        -subj "/C=CH/ST=Zurich/L=Zurich/O=stocks/CN=stocks intermediate CA" -batch
    cd ..
    openssl ca -config openssl.cnf -extensions v3_intermediate_ca -days 365000 -notext -md sha256 \
        -in intermediate/csr/intermediate.csr.pem -out intermediate/certs/intermediate.cert.pem -batch
    chmod 444 intermediate/certs/intermediate.cert.pem
    cat intermediate/certs/intermediate.cert.pem certs/ca.cert.pem > intermediate/certs/ca-chain.cert.pem
    chmod 444 intermediate/certs/ca-chain.cert.pem
    openssl ca -config intermediate/openssl.cnf -gencrl -out intermediate/crl/intermediate.crl.pem
    cat crl/ca.crl.pem intermediate/crl/intermediate.crl.pem > intermediate/crl/whole.crl.pem
    
    ## Server certificate
    cd intermediate
    openssl genrsa -out private/server.key.pem 4096
    chmod 400 private/server.key.pem
    openssl req -config openssl.cnf -new -sha256 -key private/server.key.pem -out csr/server.csr.pem \
        -subj "/C=CH/ST=Zurich/L=Zurich/O=stocks/CN=stocks server" -batch
    openssl ca -config openssl.cnf -extensions server_cert -days 365000 -notext -md sha256 \
        -in csr/server.csr.pem -out certs/server.cert.pem -batch
    chmod 444 certs/server.cert.pem
        
