@startuml

' Error handling and Conflict resolution

' Data refresh

package business {

    together {

        interface LocationListInteractor {
            getLocations(): LiveData<LocationForList>
        }

        interface LocationListIdResolver {
            getLocationIdForListItemPosition(int listItemPosition): LiveData<int>
        }

        class LocationListInteractorImpl {
            - LiveData<Location> locations
        }

        LocationListInteractorImpl --> LocationRepository
        LocationListInteractorImpl -up-|> LocationListInteractor
        LocationListInteractorImpl -up-|> LocationListIdResolver
    }

    together {
        interface LocationDeleter {
            deleteLocation(int listItemPosition)
        }

        class LocationDeleteBackgroundJob {
            - Scheduler
            - LocationDeleteInteractor
        }

        LocationDeleteBackgroundJob --|> LocationDeleter
        LocationDeleteBackgroundJob --> Scheduler
        LocationDeleteBackgroundJob --> LocationDeleteInteractor
    }

    class LocationDeleteInteractorImpl {
        - LocationDeleteService
        - LocationRepository
        - LocationListIdResolver
    }

    LocationDeleteInteractorImpl -up-|> LocationDeleteInteractor
    LocationDeleteInteractorImpl --> LocationDeleteService
    LocationDeleteInteractorImpl --> LocationRepository
    LocationDeleteInteractorImpl --> LocationListIdResolver

    interface LocationDeleteInteractor {
        deleteLocation(int listItemPosition)
    }

    interface LocationRepository {
        getLocations(): LiveData<List<Location>>
        getLocation(int id): LocationForDeletion
    }

    interface LocationDeleteService {
        deleteLocation(LocationForDeletion): StatusCode
    }

    interface Scheduler {
        execute(Job)
    }

    interface SchedulerStatusInteractor {
        getNumberOfRunningJobs(): LiveData<int>
    }

    class SchedulerStatusInteractorImpl {
        - SchedulerStatusReporter
    }

    SchedulerStatusInteractorImpl --|> SchedulerStatusInteractor
    SchedulerStatusInteractorImpl --> SchedulerStatusReporter

    interface SchedulerStatusReporter {
        getNumberOfRunningJobs(): LiveData<int>
    }

    interface Synchroniser {
        synchronise()
    }

    class SynchroniserBackgroundJob {
        - Scheduler
        - SynchroniseInteractor
    }

    SynchroniserBackgroundJob --|> Synchroniser
    SynchroniserBackgroundJob --> Scheduler
    SynchroniserBackgroundJob --> SynchroniseInteractor

    interface SynchroniseInteractor {
        synchronise()
    }

    class SynchroniseInteractorImpl {
        - SynchronisationRepository
        - RemoteUpdateService
    }

    SynchroniseInteractorImpl --|> SynchroniseInteractor
    SynchroniseInteractorImpl --> SynchronisationRepository
    SynchroniseInteractorImpl --> RemoteUpdateService

    interface RemoteUpdateService {
        getUpdates(): List<Update>
        getLocations(): List<LocationForSynchronisation>
    }

    RemoteUpdateService --> LocationForSynchronisation

    interface SynchronisationRepository {
        getUpdates(): List<Update>
        writeUpdates(List<Update>)
        writeLocations(List<LocationForSynchronisation>)
    }

    SynchronisationRepository --> Update

    class Update <<DS>> {
        table: String
        lastUpdate: OffsetDateTime
    }

    class LocationForDeletion <<DS>> {
        id: int
        version: int
    }

    class Location <<DS>> {
        id: int
        name: String
    }

    class LocationForSynchronisation <<DS>> {
        id: integer
        version: integer
        validTimeStart: OffsetDateTime
        validTimeEnd: OffsetDateTime
        transactionTimeStart: OffsetDateTime
        transactionTimeEnd: OffsetDateTime
        initiates: integer
        name: String
        description: String
    }

    class LocationForList <<DS>> {
        name: String
    }

    class Job <<DS>> {
        name: int
        Runnable
    }

    LocationListInteractorImpl --> Location
    LocationListInteractorImpl --> LocationForList
    LocationRepository --> Location
    LocationDeleteInteractorImpl --> LocationForDeletion
}

package database {

    class LocationRepositoryImpl {
        - LocationDao
    }

    LocationRepositoryImpl -up-|> LocationRepository
    LocationRepositoryImpl --> LocationDao

    class LocationDao {
        getLocations(): LiveData<List<LocationDbEntity>>
        getLocation(int id): LocationDbEntity
    }

    class SynchronisationDao {
    }

    SynchronisationDao --> UpdateDbEntity
    SynchronisationDao --|> SynchronisationRepository

    class LocationDbEntity <<DS>> {
        id: integer
        version: integer
        validTimeStart: OffsetDateTime
        validTimeEnd: OffsetDateTime
        transactionTimeStart: OffsetDateTime
        transactionTimeEnd: OffsetDateTime
        initiates: integer
        name: String
        description: String
    }

    class UpdateDbEntity <<DS>> {
        table: String
        lastUpdate: OffsetDateTime
    }

    LocationRepositoryImpl --> LocationDbEntity
    LocationDao --> LocationDbEntity
}

package presenter {
    class LocationViewModel {
        - LocationListInteractor
        - LocationDeleter
        - Synchroniser
        getLocations(): LiveData<LocationForList>
        addLocation(): LiveData<LocationListNavigationArgs>
        deleteLocation(int listItemPosition)
        editLocation(int listItemPosition): LiveData<LocationListNavigationArgs>
        synchronise()
    }

    LocationViewModel --> LocationListInteractor
    LocationViewModel --> LocationDeleter
    LocationViewModel --> SynchroniseInteractor

    class BackgroundJobViewModel {
        - SchedulerStatusInteractor
        getNumberOfRunningJobs(): LiveData<int>
        showRunningJobs(): LiveData<NavigationArgs>
    }

    BackgroundJobViewModel --> SchedulerStatusInteractor
}

package view {
    class LocationListFragment {
        - LocationViewModel
        onItemSwipedRight(View item)
        onItemClicked(View item)
        onAddItem(View button)
        onSwipeToRefresh()
    }

    LocationListFragment --> LocationViewModel
    LocationListFragment *-- LocationListAdapter

    class LocationListAdapter {
        data: List<LocationForList>
        setData(List<LocationForList>)
    }

    LocationListAdapter o-- LocationViewHolder

    class LocationViewHolder {
        name: TextField
        setName(String name)
        getListItemPosition(): int
    }

    class MainActivity {
        - BackgroundJobViewModel
        onBackgroundJobsClicked()
    }

    MainActivity *-- BackgroundJobView
    MainActivity --> BackgroundJobViewModel

    class BackgroundJobView {
        setRunningJobs(int jobs)
    }
}

package execution {

    class SchedulerImpl {
        - LiveData<int> numberOfJobs
        - LiveData<List<Job>> jobs
        - executor
    }

    SchedulerImpl --|> SchedulerStatusReporter
    SchedulerImpl --|> Scheduler
    SchedulerImpl --> Executor
    SchedulerImpl --> Job

    class Executor {
        threads
        execute(Runnable)
    }
}

package server {
    interface Api {
        getUpdates(): List<Update>
        deleteLocation(int id, int version): StatusCode
    }

    class LocationDeleteServiceImpl {
        - Api
    }

    LocationDeleteServiceImpl --> Api
    LocationDeleteServiceImpl --|> LocationDeleteService

    class SynchronisationService {
        - Api
    }

    SynchronisationService --|> RemoteUpdateService
}

@enduml
