@startuml

class User {
    {static} ID: int
    version: int
    valid_time_start: OffsetDateTime
    valid_time_end: OffsetDateTime
    transaction_time_start: OffsetDateTime
    transaction_time_end: OffsetDateTime
    name: String
}

class User_device {
    {static} ID: int
    version: int
    valid_time_start: OffsetDateTime
    valid_time_end: OffsetDateTime
    transaction_time_start: OffsetDateTime
    transaction_time_end: OffsetDateTime
    name: String
}

package Food <<Frame>> {

    class Location {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        name: String
        description: String
    }

    class Food {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        name: String
        to_buy: boolean
        expiration_offset: Period
        description: String
    }

    class Food_item {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        eat_by: OffsetDateTime
    }

    class EAN_number {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        number: String
    }
}

package Recipes <<Frame>> {

    class recipe {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        name: String
        instructions: String
        duration: Duration
    }

    class recipe_ingredient {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        amount: int
    }

    class recipe_product {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        amount: int
    }

    class scaled_unit {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        scale: BigDecimal
    }

    class unit {
        {static} ID: int
        version: int
        valid_time_start: OffsetDateTime
        valid_time_end: OffsetDateTime
        transaction_time_start: OffsetDateTime
        transaction_time_end: OffsetDateTime
        name: String
        abbreviation: String
    }
}

class Updates {
    {static} ID: int
    table_name: String
    last_update: OffsetDateTime
}

package "Only Server" {
    class Ticket {
        {static} ID: int
        ticket: String
        created_on: OffsetDateTime
    }
}

package "Only Client" {
    class Config {
        {static} key: String
        value: String
    }
}

package "Only Android" {
    class SearchSuggestion {
        {static} term: String
        last_queried: OffsetDateTime
    }
}

Location --> User_device : initiates
Food --> User_device : initiates
User --> User_device : initiates
User_device --> User_device : initiates
Food_item --> User_device : initiates
EAN_number --> User_device : initiates
recipe --> User_device : initiates
recipe_ingredient --> User_device : initiates
recipe_product --> User_device : initiates
unit --> User_device : initiates
scaled_unit --> User_device : initiates

User_device --> User : belongs_to

EAN_number --> Food : identifies

Food --> Location : location?
Food --> scaled_unit : store_unit

Food_item --> Location : stored_in
Food_item --> Food : of_type
Food_item --> User : buys
Food_item --> User_device : registers

recipe_ingredient --> recipe : recipe
recipe_ingredient --> Food : ingredient
recipe_ingredient --> scaled_unit : unit

recipe_product --> recipe : recipe
recipe_product --> Food : product
recipe_product --> scaled_unit : unit

scaled_unit --> unit : unit

Ticket --> User_device : belongs_device

@enduml
