skinparam classFontSize 24
skinparam packageFontSize 24
skinparam arrowFontSize 20
skinparam classAttributeFontSize 20
skinparam participantFontSize 24
skinparam actorFontSize 24
skinparam databaseFontSize 24
skinparam classBackgroundColor Gold
skinparam packageBackgroundColor PaleGreen
skinparam SequenceGroupFontSize 24
skinparam SequenceGroupHeaderFontSize 24
skinparam notefontsize 20
