' stocks is client-server program to manage a household's food stock
' Copyright (C) 2019  The stocks developers
'
' This file is part of the stocks program suite.
'
' stocks is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' stocks is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

@startuml

participant "client program"
database "client database"
participant nginx
participant tomcat
database postgresql

"client program" -> "client database" : get local update timestamps
activate "client database"

"client database" -> "client program"
deactivate "client database"

"client program" -> nginx : GET /update
activate nginx

nginx -> tomcat : GET /update
activate tomcat

tomcat -> postgresql : Get server update timestamps
activate postgresql

postgresql -> tomcat
deactivate postgresql

tomcat -> nginx : 200 OK
deactivate tomcat

nginx -> "client program" : 200 OK
deactivate nginx

alt server data more recent

"client program" -> nginx : GET /<data>
activate nginx

nginx -> tomcat : GET /<data>
activate tomcat

tomcat -> postgresql : Get requested data table
activate postgresql

postgresql -> tomcat
deactivate postgresql

tomcat -> nginx : 200 OK
deactivate tomcat

nginx -> "client program" : 200 OK
deactivate nginx

"client program" -> "client database" : Write new data to database
activate "client database"

"client database" -> "client program"
deactivate "client database"

end

"client program" -> "client database" : Write server timestamps
activate "client database"

"client database" -> "client program"
deactivate "client database"

@enduml
